import java.io.*;
import java.awt.*;
import java.applet.*;
import java.util.*;
import java.io.*;
import java.net.*;
public class screenDisplayAll extends java.awt.Dialog {
    Vector listToDisplay;
    /** Creates new form screenDisplayAll */
    public screenDisplayAll(java.awt.Frame parent,boolean modal, Vector list) {
        super (parent, modal);
        listToDisplay = list;
        initComponents ();
        //pack ();
        createList();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        button1 = new java.awt.Button();
        list1 = new java.awt.List();
        setLayout(new java.awt.BorderLayout());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        }
        );
        
        button1.setFont(new java.awt.Font ("Dialog", 0, 11));
        button1.setLabel("OK");
        button1.setName("button45");
        button1.setBackground(java.awt.Color.lightGray);
        button1.setForeground(java.awt.Color.black);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        }
        );
        
        add(button1, java.awt.BorderLayout.SOUTH);
        
        
        list1.setFont(new java.awt.Font ("Dialog", 0, 11));
        list1.setBackground(java.awt.Color.white);
        list1.setForeground(java.awt.Color.black);
        
        add(list1, java.awt.BorderLayout.CENTER);
        
        //pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(600, 400));
        setLocation((screenSize.width-400)/2,(screenSize.height-400)/2);
    }//GEN-END:initComponents

  private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        setVisible (false);
        dispose ();
  }//GEN-LAST:event_button1ActionPerformed

  private void createList(){
             for(int i = 0; i< listToDisplay.size(); i++){     
            list1.add((String)listToDisplay.elementAt(i));
			System.out.println(listToDisplay.elementAt(i));
        }
  }
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

}
