import java.io.*;
import java.awt.*;
import java.applet.*;
import java.util.*;
import java.io.*;
import java.net.*;
public class screenRequestMaintenance extends java.awt.Dialog {

    screenTenant tenantScreen;
    /** Creates new form screenRequestMaintenance */
    public screenRequestMaintenance(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        tenantScreen = (screenTenant)parent;
        initComponents ();
        pack ();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panel14 = new java.awt.Panel();
        label9 = new java.awt.Label();
        textField9 = new java.awt.TextField();
        label10 = new java.awt.Label();
        textField10 = new java.awt.TextField();
        checkbox13 = new java.awt.Checkbox();
        checkbox14 = new java.awt.Checkbox();
        checkbox15 = new java.awt.Checkbox();
        checkbox16 = new java.awt.Checkbox();
        checkbox17 = new java.awt.Checkbox();
        checkbox18 = new java.awt.Checkbox();
        checkbox19 = new java.awt.Checkbox();
        checkbox20 = new java.awt.Checkbox();
        checkbox21 = new java.awt.Checkbox();
        checkbox22 = new java.awt.Checkbox();
        checkbox23 = new java.awt.Checkbox();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        label13 = new java.awt.Label();
        setLayout(new java.awt.BorderLayout());
        setTitle("Request Maintenance");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        }
        );
        
        panel14.setLayout(new java.awt.GridLayout(5, 4));
        panel14.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel14.setName("panel20");
        panel14.setBackground(new java.awt.Color (204, 204, 204));
        panel14.setForeground(java.awt.Color.black);
        
        label9.setFont(new java.awt.Font ("Dialog", 0, 11));
          label9.setName("label20");
          label9.setBackground(new java.awt.Color (204, 204, 204));
          label9.setForeground(java.awt.Color.black);
          label9.setText("Apartment Num");
          panel14.add(label9);
          
          
        textField9.setBackground(java.awt.Color.white);
          textField9.setName("textfield14");
          textField9.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField9.setForeground(java.awt.Color.black);
          panel14.add(textField9);
          
          
        label10.setFont(new java.awt.Font ("Dialog", 0, 11));
          label10.setName("label21");
          label10.setBackground(new java.awt.Color (204, 204, 204));
          label10.setForeground(java.awt.Color.black);
          label10.setText("Date Filed");
          panel14.add(label10);
          
          
        textField10.setBackground(java.awt.Color.white);
          textField10.setName("textfield15");
          textField10.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField10.setForeground(java.awt.Color.black);
          panel14.add(textField10);
          
          
        checkbox13.setBackground(new java.awt.Color (204, 204, 204));
          checkbox13.setName("checkbox15");
          checkbox13.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox13.setForeground(java.awt.Color.black);
          checkbox13.setLabel("Bedroom");
          panel14.add(checkbox13);
          
          
        checkbox14.setBackground(new java.awt.Color (204, 204, 204));
          checkbox14.setName("checkbox16");
          checkbox14.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox14.setForeground(java.awt.Color.black);
          checkbox14.setLabel("BathRoom");
          panel14.add(checkbox14);
          
          
        checkbox15.setBackground(new java.awt.Color (204, 204, 204));
          checkbox15.setName("checkbox17");
          checkbox15.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox15.setForeground(java.awt.Color.black);
          checkbox15.setLabel("LivingRoom");
          panel14.add(checkbox15);
          
          
        checkbox16.setBackground(new java.awt.Color (204, 204, 204));
          checkbox16.setName("checkbox18");
          checkbox16.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox16.setForeground(java.awt.Color.black);
          checkbox16.setLabel("Dining Room");
          panel14.add(checkbox16);
          
          
        checkbox17.setBackground(new java.awt.Color (204, 204, 204));
          checkbox17.setName("checkbox19");
          checkbox17.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox17.setForeground(java.awt.Color.black);
          checkbox17.setLabel("Water");
          panel14.add(checkbox17);
          
          
        checkbox18.setBackground(new java.awt.Color (204, 204, 204));
          checkbox18.setName("checkbox20");
          checkbox18.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox18.setForeground(java.awt.Color.black);
          checkbox18.setLabel("Electrical");
          panel14.add(checkbox18);
          
          
        checkbox19.setBackground(new java.awt.Color (204, 204, 204));
          checkbox19.setName("checkbox21");
          checkbox19.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox19.setForeground(java.awt.Color.black);
          checkbox19.setLabel("Gas");
          panel14.add(checkbox19);
          
          
        checkbox20.setBackground(new java.awt.Color (204, 204, 204));
          checkbox20.setName("checkbox22");
          checkbox20.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox20.setForeground(java.awt.Color.black);
          checkbox20.setLabel("Floor");
          panel14.add(checkbox20);
          
          
        checkbox21.setBackground(new java.awt.Color (204, 204, 204));
          checkbox21.setName("checkbox23");
          checkbox21.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox21.setForeground(java.awt.Color.black);
          checkbox21.setLabel("Wall");
          panel14.add(checkbox21);
          
          
        checkbox22.setBackground(new java.awt.Color (204, 204, 204));
          checkbox22.setName("checkbox24");
          checkbox22.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox22.setForeground(java.awt.Color.black);
          checkbox22.setLabel("Outside");
          panel14.add(checkbox22);
          
          
        checkbox23.setBackground(new java.awt.Color (204, 204, 204));
          checkbox23.setName("checkbox25");
          checkbox23.setFont(new java.awt.Font ("Dialog", 0, 11));
          checkbox23.setForeground(java.awt.Color.black);
          checkbox23.setLabel("Ceiling");
          panel14.add(checkbox23);
          
          
        label11.setFont(new java.awt.Font ("Dialog", 0, 11));
          label11.setName("label22");
          label11.setBackground(new java.awt.Color (204, 204, 204));
          label11.setForeground(java.awt.Color.black);
          panel14.add(label11);
          
          
        label12.setFont(new java.awt.Font ("Dialog", 0, 11));
          label12.setName("label23");
          label12.setBackground(new java.awt.Color (204, 204, 204));
          label12.setForeground(java.awt.Color.black);
          panel14.add(label12);
          
          
        button5.setFont(new java.awt.Font ("Dialog", 0, 11));
          button5.setLabel("Back");
          button5.setName("button14");
          button5.setBackground(java.awt.Color.lightGray);
          button5.setForeground(java.awt.Color.black);
          button5.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button5ActionPerformed(evt);
              }
          }
          );
          panel14.add(button5);
          
          
        button6.setFont(new java.awt.Font ("Dialog", 0, 11));
          button6.setLabel("Submit");
          button6.setName("button15");
          button6.setBackground(java.awt.Color.lightGray);
          button6.setForeground(java.awt.Color.black);
          button6.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button6ActionPerformed(evt);
              }
          }
          );
          panel14.add(button6);
          
          
        label13.setFont(new java.awt.Font ("Dialog", 0, 11));
          label13.setName("label24");
          label13.setBackground(new java.awt.Color (204, 204, 204));
          label13.setForeground(java.awt.Color.black);
          panel14.add(label13);
          
          
        add(panel14, java.awt.BorderLayout.CENTER);
        
        //pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(500, 500));
        setLocation((screenSize.width-500)/2,(screenSize.height-500)/2);
    }//GEN-END:initComponents

  private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
		Vector v = new Vector();
		v.add(textField9.getText());
		v.add(textField10.getText());
		Boolean b = new Boolean(checkbox13.getState());
		v.add(b);
		b = new Boolean(checkbox14.getState());
		v.add(b);
		b = new Boolean(checkbox15.getState());
		v.add(b);
		b = new Boolean(checkbox16.getState());
		v.add(b);
		b = new Boolean(checkbox17.getState());
		v.add(b);
		b = new Boolean(checkbox18.getState());
		v.add(b);
		b = new Boolean(checkbox19.getState());
		v.add(b);
		b = new Boolean(checkbox20.getState());
		v.add(b);
		b = new Boolean(checkbox21.getState());
		v.add(b);  
		b = new Boolean(checkbox22.getState());
		v.add(b);  
		b = new Boolean(checkbox23.getState());
		v.add(b);  
		tenantScreen.requestMaintenance(v);
		
// Add your handling code here:
  }//GEN-LAST:event_button6ActionPerformed

  private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
 setVisible (false);
        dispose ();
      // Add your handling code here:
  }//GEN-LAST:event_button5ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new screenRequestMaintenance (new java.awt.Frame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel panel14;
    private java.awt.Label label9;
    private java.awt.TextField textField9;
    private java.awt.Label label10;
    private java.awt.TextField textField10;
    private java.awt.Checkbox checkbox13;
    private java.awt.Checkbox checkbox14;
    private java.awt.Checkbox checkbox15;
    private java.awt.Checkbox checkbox16;
    private java.awt.Checkbox checkbox17;
    private java.awt.Checkbox checkbox18;
    private java.awt.Checkbox checkbox19;
    private java.awt.Checkbox checkbox20;
    private java.awt.Checkbox checkbox21;
    private java.awt.Checkbox checkbox22;
    private java.awt.Checkbox checkbox23;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Label label13;
    // End of variables declaration//GEN-END:variables

}
