import java.io.*;
import java.awt.*;
import java.applet.*;
import java.util.*;
import java.io.*;
import java.net.*;
public class screenCreateNewTenent extends java.awt.Dialog {
    private screenMgr managerMenu;
    /** Creates new form screenCreateNewTenent */
    public screenCreateNewTenent(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        managerMenu = (screenMgr)parent;
        initComponents ();
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label1 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label5 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField5 = new java.awt.TextField();
        label8 = new java.awt.Label();
        textField7 = new java.awt.TextField();
        label11 = new java.awt.Label();
        textField8 = new java.awt.TextField();
        label9 = new java.awt.Label();
        textField9 = new java.awt.TextField();
        panel2 = new java.awt.Panel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        panel3 = new java.awt.Panel();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        label1.setFont(new java.awt.Font ("Dialog", 0, 11));
        label1.setName("label32");
        label1.setBackground(new java.awt.Color (204, 204, 204));
        label1.setForeground(java.awt.Color.black);
        label1.setText("Create New Tenent");
        label1.setAlignment(java.awt.Label.CENTER);
        
        add(label1, java.awt.BorderLayout.NORTH);
        
        
        panel1.setLayout(new java.awt.GridLayout(5, 4));
        panel1.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel1.setName("panel26");
        panel1.setBackground(new java.awt.Color (204, 204, 204));
        panel1.setForeground(java.awt.Color.black);
        
        label2.setFont(new java.awt.Font ("Dialog", 0, 11));
          label2.setName("label33");
          label2.setBackground(new java.awt.Color (204, 204, 204));
          label2.setForeground(java.awt.Color.black);
          label2.setText("First Name");
          panel1.add(label2);
          
          
        textField1.setBackground(java.awt.Color.white);
          textField1.setName("textfield25");
          textField1.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField1.setForeground(java.awt.Color.black);
          textField1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  textField1ActionPerformed(evt);
              }
          }
          );
          panel1.add(textField1);
          
          
        label3.setFont(new java.awt.Font ("Dialog", 0, 11));
          label3.setName("label34");
          label3.setBackground(new java.awt.Color (204, 204, 204));
          label3.setForeground(java.awt.Color.black);
          label3.setText("Last Name");
          panel1.add(label3);
          
          
        textField2.setBackground(java.awt.Color.white);
          textField2.setName("textfield26");
          textField2.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField2.setForeground(java.awt.Color.black);
          panel1.add(textField2);
          
          
        label4.setFont(new java.awt.Font ("Dialog", 0, 11));
          label4.setName("label35");
          label4.setBackground(new java.awt.Color (204, 204, 204));
          label4.setForeground(java.awt.Color.black);
          label4.setText("SSN");
          panel1.add(label4);
          
          
        textField3.setBackground(java.awt.Color.white);
          textField3.setName("textfield27");
          textField3.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField3.setForeground(java.awt.Color.black);
          panel1.add(textField3);
          
          
        label5.setFont(new java.awt.Font ("Dialog", 0, 11));
          label5.setName("label36");
          label5.setBackground(new java.awt.Color (204, 204, 204));
          label5.setForeground(java.awt.Color.black);
          label5.setText("LoginID");
          panel1.add(label5);
          
          
        textField4.setBackground(java.awt.Color.white);
          textField4.setName("textfield28");
          textField4.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField4.setForeground(java.awt.Color.black);
          panel1.add(textField4);
          
          
        label6.setFont(new java.awt.Font ("Dialog", 0, 11));
          label6.setName("label37");
          label6.setBackground(new java.awt.Color (204, 204, 204));
          label6.setForeground(java.awt.Color.black);
          label6.setText("Password");
          panel1.add(label6);
          
          
        textField5.setBackground(java.awt.Color.white);
          textField5.setName("textfield29");
          textField5.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField5.setForeground(java.awt.Color.black);
          panel1.add(textField5);
          
          
        label8.setFont(new java.awt.Font ("Dialog", 0, 11));
          label8.setName("label39");
          label8.setBackground(new java.awt.Color (204, 204, 204));
          label8.setForeground(java.awt.Color.black);
          label8.setText("Street address");
          panel1.add(label8);
          
          
        textField7.setBackground(java.awt.Color.white);
          textField7.setName("textfield31");
          textField7.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField7.setForeground(java.awt.Color.black);
		  textField7.setText("505 Lake Ave.");
		  textField7.setEditable(false);
          panel1.add(textField7);
          
          
        label11.setFont(new java.awt.Font ("Dialog", 0, 11));
          label11.setName("label52");
          label11.setBackground(new java.awt.Color (204, 204, 204));
          label11.setForeground(java.awt.Color.black);
          label11.setText("Apt #");
          panel1.add(label11);
          
          
        textField8.setBackground(java.awt.Color.white);
          textField8.setName("textfield32");
          textField8.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField8.setForeground(java.awt.Color.black);
          panel1.add(textField8);
          
          
        label9.setFont(new java.awt.Font ("Dialog", 0, 11));
          label9.setName("label40");
          label9.setBackground(new java.awt.Color (204, 204, 204));
          label9.setForeground(java.awt.Color.black);
          label9.setText("Phone Num");
          panel1.add(label9);
          
          
        textField9.setBackground(java.awt.Color.white);
          textField9.setName("textfield39");
          textField9.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField9.setForeground(java.awt.Color.black);
          panel1.add(textField9);
          
          
        panel2.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel2.setName("panel27");
          panel2.setBackground(new java.awt.Color (204, 204, 204));
          panel2.setForeground(java.awt.Color.black);
          panel1.add(panel2);
          
          
        button1.setFont(new java.awt.Font ("Dialog", 0, 11));
          button1.setLabel("Submit");
          button1.setName("button37");
          button1.setBackground(java.awt.Color.lightGray);
          button1.setForeground(java.awt.Color.black);
          button1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button1ActionPerformed(evt);
              }
          }
          );
          panel1.add(button1);
          
          
        button2.setFont(new java.awt.Font ("Dialog", 0, 11));
          button2.setLabel("Cancel");
          button2.setName("button38");
          button2.setBackground(java.awt.Color.lightGray);
          button2.setForeground(java.awt.Color.black);
          button2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button2ActionPerformed(evt);
              }
          }
          );
          panel1.add(button2);
          
          
        panel3.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel3.setName("panel28");
          panel3.setBackground(new java.awt.Color (204, 204, 204));
          panel3.setForeground(java.awt.Color.black);
          panel1.add(panel3);
          
          
        add(panel1, java.awt.BorderLayout.CENTER);
        
        //pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(300, 200));
        setLocation((screenSize.width-300)/2,(screenSize.height-200)/2);
    }//GEN-END:initComponents

  private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_textField1ActionPerformed

  private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    Vector v = new Vector();
    v.add(textField1.getText());
    v.add(textField2.getText());
    v.add(textField3.getText());
    v.add(textField4.getText());
    v.add(textField5.getText());
    v.add(textField7.getText());
    v.add(textField8.getText());
    v.add(textField9.getText());
    managerMenu.createNewTenent(v);
    setVisible (false);
    dispose ();
  }//GEN-LAST:event_button1ActionPerformed

  private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
    setVisible (false);
        dispose ();
  }//GEN-LAST:event_button2ActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    private java.awt.Label label2;
    private java.awt.TextField textField1;
    private java.awt.Label label3;
    private java.awt.TextField textField2;
    private java.awt.Label label4;
    private java.awt.TextField textField3;
    private java.awt.Label label5;
    private java.awt.TextField textField4;
    private java.awt.Label label6;
    private java.awt.TextField textField5;
    private java.awt.Label label8;
    private java.awt.TextField textField7;
    private java.awt.Label label11;
    private java.awt.TextField textField8;
    private java.awt.Label label9;
    private java.awt.TextField textField9;
    private java.awt.Panel panel2;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables

}
