import java.io.*;
import java.awt.*;
import java.applet.*;
import java.util.*;
import java.io.*;
import java.net.*;
public class screenLogin extends java.awt.Dialog {

	String home = "127.0.0.1";
	int port = 6669;
	Socket s = null;
	String serverResponse = null;

    /** Creates new form screenLogin */
    public screenLogin(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        pack ();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label1 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        panel2 = new java.awt.Panel();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        setLayout(new java.awt.BorderLayout());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        }
        );
        
        label1.setFont(new java.awt.Font ("Dialog", 0, 11));
        label1.setName("label1");
        label1.setBackground(new java.awt.Color (204, 204, 204));
        label1.setForeground(java.awt.Color.black);
        label1.setText("LOGIN");
        label1.setAlignment(java.awt.Label.CENTER);
        
        add(label1, java.awt.BorderLayout.NORTH);
        
        
        panel1.setLayout(new java.awt.GridLayout(2, 2));
        panel1.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel1.setName("panel1");
        panel1.setBackground(new java.awt.Color (204, 204, 204));
        panel1.setForeground(java.awt.Color.black);
        
        label2.setFont(new java.awt.Font ("Dialog", 0, 11));
          label2.setName("label2");
          label2.setBackground(new java.awt.Color (204, 204, 204));
          label2.setForeground(java.awt.Color.black);
          label2.setText("LOGIN ID");
          panel1.add(label2);
          
          
        textField1.setBackground(java.awt.Color.white);
          textField1.setName("textfield1");
          textField1.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField1.setForeground(java.awt.Color.black);
          textField1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  textField1ActionPerformed(evt);
              }
          }
          );
          panel1.add(textField1);
          
          
        label4.setFont(new java.awt.Font ("Dialog", 0, 11));
          label4.setName("label4");
          label4.setBackground(new java.awt.Color (204, 204, 204));
          label4.setForeground(java.awt.Color.black);
          label4.setText("PASSWORD");
          panel1.add(label4);
          
          
        textField3.setBackground(java.awt.Color.white);
          textField3.setName("textfield3");
          textField3.setFont(new java.awt.Font ("Dialog", 0, 11));
          textField3.setForeground(java.awt.Color.black);
          textField3.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  textField3ActionPerformed(evt);
              }
          }
          );
          panel1.add(textField3);
          
          
        add(panel1, java.awt.BorderLayout.CENTER);
        
        
        panel2.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel2.setName("panel2");
        panel2.setBackground(new java.awt.Color (204, 204, 204));
        panel2.setForeground(java.awt.Color.black);
        
        button3.setFont(new java.awt.Font ("Dialog", 0, 11));
          button3.setLabel("VISITOR");
          button3.setName("VISITOR");
          button3.setBackground(java.awt.Color.lightGray);
          button3.setForeground(java.awt.Color.black);
          button3.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button3ActionPerformed(evt);
              }
          }
          );
          panel2.add(button3);
          
          
        button4.setFont(new java.awt.Font ("Dialog", 0, 11));
          button4.setLabel("LOG IN");
          button4.setName("LOG IN");
          button4.setBackground(java.awt.Color.lightGray);
          button4.setForeground(java.awt.Color.black);
          button4.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  button4ActionPerformed(evt);
              }
          }
          );
          panel2.add(button4);
          
          
        add(panel2, java.awt.BorderLayout.SOUTH);
        
    }//GEN-END:initComponents

  private void textField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField3ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_textField3ActionPerformed

  private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_textField1ActionPerformed

  private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        String lgInNm = (textField1.getText());
        String pswrd = (textField3.getText());
        Socket s = null;
  	String serverResponse = null;
  	Vector reportVector = new Vector();
  	try{
  		System.out.println("Opening socket connection");
  		s = new Socket(home, port);
  		System.out.println("Socket connection established.");
  		PrintStream os = new PrintStream(s.getOutputStream());
  		DataInputStream is = new DataInputStream(s.getInputStream());
  		os.print("LOGIN\n");
                os.print(lgInNm+"\n");
                os.print(pswrd+"\n");
                if(s != null) s.close();
  	}
  	catch(Exception e){System.out.println("Error" + e);}    
  }//GEN-LAST:event_button4ActionPerformed

  private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        new screenVisitor().show();
  }//GEN-LAST:event_button3ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new screenLogin (new java.awt.Frame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    private java.awt.Label label2;
    private java.awt.TextField textField1;
    private java.awt.Label label4;
    private java.awt.TextField textField3;
    private java.awt.Panel panel2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    // End of variables declaration//GEN-END:variables

}
