
<style type="text/css">
a.email{
	font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	color: #000000;
	text-decoration: underline;
}
a.email:hover{
	font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	color: #FFFFFF;
	text-decoration: underline;
}
body
{
   text-align: center;
   margin-left: auto;
   margin-right: auto;
   background-color: #6976DD;
}
div.body
{
   width: 757px;
   height: 500px;
   border: 2px solid #09144C;
   background: #FF9900;
   /*
   margin-left: auto;
   margin-right: auto;
   text-align: center;
   position: absolute;
   padding:0px;
   */
   margin-top: 30px;
   position: relative;
   z-index:1;
   /*background-image: url(black.bmp);*/
}
div.body_main
{
   width: 100%;
   margin: 0px;
   border: 0px;
   padding: 0px;
}
div.about_photo
{
   border: 0px solid white;
   position: absolute;
   left: 25px;
   top: 170px;
   width: 220px;
   height: 250px;
}
div.about
{
   border: 0px dashed orange;
   position: absolute;
   left: 255px;
   top: 130px;
   width: 485px;
   height: 320px;
   z-index: 4;
   color: #000000;
	text-align: justify;
   font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 15px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	text-decoration: none;
}
div.photo_collage
{
   border: 0px dashed orange;
   width: 450px;
   height: 300px;
   position: absolute;
   left: 130px;
   top: 150px;
   z-index: 4;
}
div.photo_main
{
   border: 0px solid black;
   width: 350px;
   height: 300px;
   position: absolute;
   left: 50px;
   top: 150px;
   z-index: 4;
}
div.photo_album
{
   border: 0x solid green;
   width: 330px;
   height: 300px;
   position: absolute;
   justify: margin;
   padding: 10px 10px 10px 10px;
   right: 20px;
   top: 150px;
   z-index: 3;
   vertical-align: center;
}
img.mini
{
   padding: 0px;
   border: 0px;
   margin: 0px;
   position: relative;
   border: 1px solid #000000;
}
img.big
{
   padding: 0px;
   border: 0px;
   margin: 0px;
   position: relative;
   border: 1px solid #000000;
}
   div.mmSubMenu
   {
      z-index: 2; right: 25px;top:80px;
      position: absolute;
      text-align: center;
      border: 0px solid #0FF00F;
      width: 187px;
      height: 51px;
      padding: 3px 0px 0px 0px;
      margin: 0px 0px 0px 0px;
      background-image: url(images/contact_details_background.jpg);
      color:#FFFFFF;
   }
   div.mmSubMenuCell
   {
      height: 25px;
      /*
      width: <?php echo($button_width); ?>px;
      border-width: 0px;
      border-color: #000000;
      background-color: #999999;
      border-style: solid;
      padding: 0px;
      */
   }
   a.mmSubMenuCell:link{color:#000000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
   a.mmSubMenuCell:visited{color:#000000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
   a.mmSubMenuCell:hover{color:#FF0000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
</style>