<?
include("header.inc");
commonHeader("$Company","Find A Receipt");

blueFont("Arial","<b>Choose your search method...</b>");

echo "<TABLE BORDER='0' CELLPADDING='10' CELLSPACING='10'>";
echo "<FORM ACTION='./search_receipts_response.php?criteria=all' METHOD='POST'>";
echo "<tr><td>";
blueFont("Arial","Select from Order List:");
echo "</td><td align=\"center\">";
echo "&nbsp;&nbsp;<INPUT TYPE='submit' NAME='Submit' VALUE=\"Select from List\">";
echo "</td></tr></form>";
echo "<FORM ACTION='./search_receipts_response.php?criteria=order' METHOD='POST'>";
echo "<tr><td>";
blueFont("Arial","By Order Number:");
echo "</td><td>";
echo "<input type='text' name='OrderNumber' size='50'>";
echo "&nbsp;&nbsp;<INPUT TYPE='submit' NAME='Submit' VALUE='Submit'>";
echo "</td></tr></form>";

echo "<FORM ACTION='./search_receipts_response.php?criteria=name' METHOD='POST' ENCTYPE='x-www-form-urlencoded'>";
echo "<tr><td>";
blueFont("Arial","By User's Name:");
echo "</td><td>";
echo "<input type='text' name='User' size='50'>";
echo "&nbsp;&nbsp;<INPUT TYPE='submit' NAME='Submit' VALUE='Submit'>";
echo "</td></tr></form>";

$Mn=date("m");
$LMn=date("F");
$Dy=date("d");
$Yr=date("Y");
echo "<FORM ACTION='./search_receipts_response.php?criteria=date' METHOD='POST' ENCTYPE='x-www-form-urlencoded'>";
echo "<tr><td>";
blueFont("Arial","By Date:");
echo "</td><td>";
echo "<select name='Month'>";
echo "<option value='$Mn'> $LMn </option>";
echo "<option value=''> Any Month </option>";
echo "<option value='01'> January </option>";
echo "<option value='02'> February </option>";
echo "<option value='03'> March </option>";
echo "<option value='04'> April </option>";
echo "<option value='05'> May </option>";
echo "<option value='06'> June </option>";
echo "<option value='07'> July </option>";
echo "<option value='08'> August </option>";
echo "<option value='09'> September </option>";
echo "<option value='10'> October </option>";
echo "<option value='11'> November </option>";
echo "<option value='12'> December </option>";
echo "</select>";
echo "&nbsp; &nbsp; &nbsp; ";
echo "<select name='Day'>";
echo "<option value='$Dy'> $Dy </option>";
echo "<option value=''> Any Day </option>";
echo "<option value='01'> 01 </option>";
echo "<option value='02'> 02 </option>";
echo "<option value='03'> 03 </option>";
echo "<option value='04'> 04 </option>";
echo "<option value='05'> 05 </option>";
echo "<option value='06'> 06 </option>";
echo "<option value='07'> 07 </option>";
echo "<option value='08'> 08 </option>";
echo "<option value='09'> 09 </option>";
echo "<option value='10'> 10 </option>";
echo "<option value='11'> 11 </option>";
echo "<option value='12'> 12 </option>";
echo "<option value='13'> 13 </option>";
echo "<option value='14'> 14 </option>";
echo "<option value='15'> 15 </option>";
echo "<option value='16'> 16 </option>";
echo "<option value='17'> 17 </option>";
echo "<option value='18'> 18 </option>";
echo "<option value='19'> 19 </option>";
echo "<option value='20'> 20 </option>";
echo "<option value='21'> 21 </option>";
echo "<option value='22'> 22 </option>";
echo "<option value='23'> 23 </option>";
echo "<option value='24'> 24 </option>";
echo "<option value='25'> 25 </option>";
echo "<option value='26'> 26 </option>";
echo "<option value='27'> 27 </option>";
echo "<option value='28'> 28 </option>";
echo "<option value='29'> 29 </option>";
echo "<option value='30'> 30 </option>";
echo "<option value='31'> 31 </option>";
echo "</select>";
echo "&nbsp; &nbsp; &nbsp; ";

$d1=bcsub($Yr,5);
$d2=bcsub($Yr,4);
$d3=bcsub($Yr,3);
$d4=bcsub($Yr,2);
$d5=bcsub($Yr,1);

echo "<select name='Year'>";
echo "<option value='$Yr'> $Yr </option>";
echo "<option value=''> Any Year </option>";
echo "<option value='$d1'> $d1 </option>";
echo "<option value='$d2'> $d2 </option>";
echo "<option value='$d3'> $d3 </option>";
echo "<option value='$d4'> $d4 </option>";
echo "<option value='$d5'> $d5 </option>";
echo "</select>";
echo "&nbsp;&nbsp; <INPUT TYPE='submit' NAME='Submit' VALUE='Submit'>";
echo "</td></tr></form></TABLE>";


adminFooter();
?>
