<html>
<head>
   <title> <?php echo($title); ?> </title>
   <script language="JavaScript" type="text/javascript" src="../form_check.js"></script>
   <style type="text/css">@import "../template_client.css";</style>
   <?
   /*
   <script language="JavaScript" type="text/javascript" src="<?php echo($_SERVER["DOCUMENT_ROOT"]); ?>/form_check.js"></script>
   <style type="text/css">@import "<?php echo($_SERVER["DOCUMENT_ROOT"]); ?>/template_client.css";</style>
   */
   ?>
</head>
</head>