<?php
  include("./classes/DB_Mgr.inc");
  error_reporting(E_ALL);
	/*
  	* This header file connects us to the database which will
  	*  be used.
  	*/
$row_color = "#999999";
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 //EN">
<HTML>
<HEAD>
<TITLE><?=$title?></TITLE>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<link rel="stylesheet" type="text/css" href="./style.css"/>
</head>
<BODY>
