
         <td width="250px" style="background-color: #006390; vertical-align: top;">  
            <table class="menuTable" style="top:100px;">
               <TR>
                  <TD STYLE="padding: 20px">
                     <a href="index.php"><img src="black_white_logo.gif" style="border-style: none;"></a>
                  </TD>
               </TR>
               <tr> 
                  <td><a href="index.php" class="whiteMenu">HOME</div></td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="#" class="whiteMenu">ABOUT DURHAM AND BATES</a></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="history.php" class="whiteSubMenu">HISTORY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">CULTURE</a></td>
                        </tr>
                        <tr> 
                           <td><a href="giving.php" class="whiteSubMenu">CHARITABLE GIVING</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="#" class="whiteMenu">INDUSTRY & PRODUCT SPECIALTIES</a></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="construction.php" class="whiteSubMenu">CONSTRUCTION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">MANUFACTURING</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">TECHNOLOGY/LIFE SCIENCES</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">ENVIRONMENTAL & POLLUTION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">WORKERS' COMPENSATION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">DIRECTORS & OFFICES</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">EMPLOYMENT PRACTICES LIABILITY</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="#" class="whiteMenu">DEPARTMENTS</a></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="commercial_lines.php" class="whiteSubMenu">COMMERCIAL LINES</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">MARINE</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">MANAGEMENT LIABILITY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">WORKERS' COMPENSATION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">PERSONAL INSURANCE</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="#" class="whiteMenu">CONTACT US</a></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">ASSOCIATE DIRECTORY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">LOCATION/DIRECTIONS</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="#" class="whiteMenu">CLIENT ACCESS</a></td>
               </tr>
               <tr>
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="#" class="whiteSubMenu">LOGIN</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr>
                  <td>&nbsp;</td>
               </tr>
            </table>
         </td>