<?php
class Settings
{
   /*
   var $server = array("dbates" => "server");
   var $db = array("dbates" => "dbates");
   var $id = array("dbates" => "c8h10n4o2");
   var $pwd = array("dbates" => "Zoolu4");
   */
   var $server = array("dbates" => "sqlc2.megasqlservers.com");
   #var $server = array("dbates" => "localhost");
   var $db = array("dbates" => "default_dbates_com");
   var $id = array("dbates" => "dbatescom4486303");
   var $pwd = array("dbates" => "hurd7bye");
   
   function Settings()
   {
   }
}
?>