
<div id="Footer">
   <div class="menuGroup">
      <div class="cat">Environments</div>
      <div class="subCat"><a href="./dbs.php?app=TIERS">TIERS DBs</a></div>
      <div class="subCat"><a href="./mqs.php">MQs</a></div>
      <div class="subCat"><a href="./apps_all.php">ALL APPS</a></div>
      <div class="subCat"><a href="./apps_batch.php">TIERS BATCH</a></div>
      <div class="subCat"><a href="./apps_online.php">TIERS ONLINE</a></div>
   </div>
   <div class="menuGroup">
      <div class="cat">Reference</div>
      <div class="subCat"><a href="./reference/websphere.php">WebSphere Reference</a></div>
      <div class="subCat"><a href="./reference/wica.php">WICA</a></div>
      <div class="subCat"><a href="./reference/clearcase.php">ClearCase</a></div>
      <div class="subCat"><a href="./reference/unix.php">Unix Reference</a></div>
      <div class="subCat"><a href="./reference/boxes.php">Boxes</a></div>
      <div class="subCat"><a href="./reference/vi.pdf" target="_blank">VI Reference</a></div>
   </div>
   <div class="menuGroup">
      <div class="cat">Links</div>
      <div class="subCat"><a href="http://iepsww001/" target="_blank">TIERS Support</a></div>
      <div class="subCat"><a href="https://itg-taa.accenture.com/itg/dashboard/app/portal/PageView.jsp" target="_blank">ITG</a></div>
      <div class="subCat">
         ITG Search #
         <form name="itgSearch" action="https://itg-taa.accenture.com/itg/web/knta/crt/RequestDetail.jsp" method="get" style="margin-top: 0px;" target="_blank">
            <input type="text" id="searchITGtext" name="REQUEST_ID"></input>
            <input type="submit" id="searchITGbutton" name="Search" value="Search" onmouseover="if(this.style){this.id='searchITGbuttonHover';}" onmouseout="if(this.style){this.id='searchITGbutton';}">
         </form>
      </div>
   </div>
   <div class="menuGroup">
      <div class="cat">Procedures</div>
      <div class="subCat"><a href="./procedures/prep_env_for_dev.php">Prep Envt for Dev</a></div>
      <div class="subCat"><a href="./procedures/repo_access.php">Repo Access</a></div>
      <div class="subCat"><a href="./procedures/sas_triggers.php">SAS Triggers</a></div>
      <div class="subCat"><a href="./procedures/aging_envt_setup.php">AGING Setup</a></div>
   </div>
</div>

