<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script type="text/javascript" src="script.js"></script>
    <script language="Javascript" src="autosuggest.js"></script>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
    <title><?php echo($title); ?></title>
    <style type="text/css" media="all">@import "./style.css";</style>
</head>

<body>

<div id="Header">
<?php include("menu.inc"); ?>
</div>



