   <span class="menu_center">
      <div class="menuGroup">
         <div class="cat">Environments</div>
         <div class="subCat"><a href="./dbs.php?app=TIERS">TIERS DBs</a></div>
         <div class="subCat"><a href="./mqs.php">MQs</a></div>
         <div class="subCat"><a href="./apps_all.php">ALL APPS</a></div>
         <div class="subCat"><a href="./apps_batch.php">TIERS BATCH</a></div>
         <div class="subCat"><a href="./apps_online.php">TIERS ONLINE APPS</a></div>
         <div class="subCat"><a href="./apps_online_servers.php">TIERS ONLINE SERVERS</a></div>
      </div>
      <div class="menuGroup">
         <div class="cat">Reference</div>
         <div class="subCat"><a href="./ref_websphere.php">WebSphere Reference</a></div>
         <div class="subCat"><a href="./ref_wica.php">WICA</a></div>
         <div class="subCat"><a href="./ref_clearcase.php">ClearCase</a></div>
         <div class="subCat"><a href="./ref_unix.php">Unix Reference</a></div>
         <div class="subCat"><a href="./ref_boxes.php">Boxes</a></div>
      </div>
      <div class="menuGroup">
         <div class="cat">Links</div>
         <div class="subCat"><a href="http://iepsww001/" target="_blank">TIERS Support</a></div>
         <div class="subCat"><a href="http://workbench/wiki" target="_blank">WIKI</a></div>
         <div class="subCat">
            ITG Search #
            <form name="itgSearch" action="https://itg-taa.accenture.com/itg/web/knta/crt/RequestDetail.jsp" method="get" style="margin-top: 0px;" target="_blank">
               <input type="text" id="searchITGtext" name="REQUEST_ID"></input>
               <input type="submit" id="searchITGbutton" name="Search" value="Search" onmouseover="if(this.style){this.id='searchITGbuttonHover';}" onmouseout="if(this.style){this.id='searchITGbutton';}">
            </form>
         </div>
      </div>
      <div class="menuGroup">
         <div class="cat">Login</div>
         <div class="subCat">
            <table border=0 style="border: 0px">
               <form method="post" name="loginForm" action="login_process.php">
                  <tr><td>ID:</td><td><input type="text" name="id" class="search"></td></tr>
                  <tr><td>PWD:</td><td><input type="text" name="pwd" class="search"></td></tr>
                  <tr><td colspan="2" align="center"><input type="submit" class="search" name="Login" value="Login"></td></tr>
               </form>
            </table>
         </div>
      </div>
   </span>