
         <td width="230px" style="background-color: #006390; vertical-align: top;">  
            <table class="menuTable" style="top:100px;">
               <TR>
                  <TD STYLE="padding: 15px">
                     <a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/index.php"><img src="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/public_images/logo.gif" style="border-style: none;" alt="Durham and Bates"></a>
                  </TD>
               </TR>
               <tr> 
                  <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/index.php" class="whiteMenu">HOME</div></td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><div class="whiteMenu">ABOUT DURHAM AND BATES</div></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/history.php" class="whiteSubMenu">HISTORY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/associations.php" class="whiteSubMenu">ASSOCIATIONS</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/giving.php" class="whiteSubMenu">CHARITABLE GIVING</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><div class="whiteMenu">INDUSTRY & PRODUCT SPECIALTIES</div></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_construction.php" class="whiteSubMenu">CONSTRUCTION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_manufacturing.php" class="whiteSubMenu">MANUFACTURING</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_food_processing.php" class="whiteSubMenu">FOOD PROCESSING</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/depts_marine.php" class="whiteSubMenu">MARINE INSURANCE</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_technology.php" class="whiteSubMenu">TECHNOLOGY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_life_sciences.php" class="whiteSubMenu">LIFE SCIENCES</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_environmental.php" class="whiteSubMenu">ENVIRONMENTAL & POLLUTION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_workers_comp.php" class="whiteSubMenu">WORKERS' COMPENSATION</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_directors.php" class="whiteSubMenu">DIRECTORS & OFFICERS</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_employment_practices.php" class="whiteSubMenu">EMPLOYMENT PRACTICES LIABILITY</a></td>
                        </tr>
                        <!--
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/spec_other.php" class="whiteSubMenu">OTHER SPECIALTIES</a></td>
                        </tr>
                        -->
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><div class="whiteMenu">DEPARTMENTS</div></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/depts_commercial_lines.php" class="whiteSubMenu">COMMERCIAL LINES</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/depts_marine.php" class="whiteSubMenu">MARINE</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/depts_mgt_liability.php" class="whiteSubMenu">MANAGEMENT LIABILITY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/depts_personal.php" class="whiteSubMenu">PERSONAL RISK</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/news.php" class="whiteMenu">NEWS AND EVENTS</a></td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><div class="whiteMenu">CONTACT US</div></td>
               </tr>
               <tr> 
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/directory.php" class="whiteSubMenu">ASSOCIATE DIRECTORY</a></td>
                        </tr>
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/map.php" class="whiteSubMenu">LOCATION / DIRECTIONS</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr> 
                  <td>&nbsp;</td>
               </tr>
               <tr> 
                  <td><div class="whiteMenu">CLIENT ACCESS</div></td>
               </tr>
               <tr>
                  <td>
                     <table class="subMenuTable">
                        <tr> 
                           <td><a href="http://<?php echo($_SERVER["SERVER_NAME"]); ?>/login.php" class="whiteSubMenu">LOGIN</a></td>
                        </tr>
                     </table>
                  </td>
               </tr>
               <tr>
                  <td>&nbsp;</td>
               </tr>
            </table>
         </td>