<?php
class Settings_oohaheats
{
   //var $server = "PSTEST, 2433";
   var $server = "localhost";
   var $db = "aubri_cookbook";
   var $id = "aubri";
   var $pwd = "z00l00";
   
   //var $tables = array("site" => "SI_SITE", "phone_line" =>"SI_PHONE_LINE", "phone_company"=>"SI_PHONE_CO", "phone_type"=>"SI_PHONE_TYPE", "amenity_type"=>"SI_AMENITY_TYPE", "amenity_list"=>"SI_AMENITY_LIST");
   
   function Settings_oohaheats()
   {
   }
}
?>