<div id="logo" style="position:absolute; left:31px; top:7px; width:153px; height:121px; z-index:1"> 
  <table border="0" cellpadding="0" cellspacing="0" width="152">
<!-- fwtable fwsrc="images/logo.png" fwbase="logo.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
  <tr>
   <td><img src="images/spacer.gif" width="18" height="1" border="0" alt=""></td>
   <td><img src="images/spacer.gif" width="107" height="1" border="0" alt=""></td>
   <td><img src="images/spacer.gif" width="27" height="1" border="0" alt=""></td>
   <td><img src="images/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>

  <tr>
   <td colspan="3"><img name="logo_r1_c1" src="images/logo_r1_c1.gif" width="152" height="5" border="0" alt=""></td>
   <td><img src="images/spacer.gif" width="1" height="5" border="0" alt=""></td>
  </tr>
  <tr>
   <td rowspan="2"><img name="logo_r2_c1" src="images/logo_r2_c1.gif" width="18" height="167" border="0" alt="Web Design"></td>
        <td><a href="http://www.caffeinewebdesign.com"><img name="logo" src="images/logo.gif" width="107" height="153" border="0" alt="Web Design"></a></td>
   <td rowspan="2"><img name="logo_r2_c3" src="images/logo_r2_c3.gif" width="27" height="167" border="0" alt="Web Design"></td>
   <td><img src="images/spacer.gif" width="1" height="153" border="0" alt=""></td>

  </tr>
  <tr>
   <td><img name="logo_r3_c2" src="images/logo_r3_c2.gif" width="107" height="14" border="0" alt=""></td>
   <td><img src="images/spacer.gif" width="1" height="14" border="0" alt=""></td>
  </tr>
</table>
</div>