<div id="menu" style="position:absolute; left:182px; top:65px; width:160px; height:47px; z-index:1"> 
   <table border="0" cellpadding="0" cellspacing="0" width="592">
      <!-- fwtable fwsrc="images/top_menu_hollow.png" fwbase="top_menu_hollow.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
      <tr>
         <td><img src="images/spacer.gif" width="97" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="3" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="96" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="2" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="97" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="2" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="97" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="2" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="97" height="1" border="0" alt=""></td>         
         <td><img src="images/spacer.gif" width="2" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="97" height="1" border="0" alt=""></td>
         <td><img src="images/spacer.gif" width="1" height="1" border="0" alt=""></td>
      </tr>
      
      <tr>
         <td><a href="index.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('home','','images/home_down.gif',1);"><img name="home" src="images/home_up.gif" width="97" height="47" border="0" alt=""></a></td>
         <td colspan="3"><a href="services.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('services','','images/services_down.gif',1);"><img name="services" src="images/services_up.gif" width="101" height="47" border="0" alt=""></a></td>
         <td colspan="2"><a href="process.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('process','','images/process_down.gif',1);"><img name="process" src="images/process_up.gif" width="99" height="47" border="0" alt=""></a></td>
         <td colspan="2"><a href="portfolio.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('portfolio','','images/portfolio_down.gif',1);"><img name="portfolio" src="images/portfolio_up.gif" width="99" height="47" border="0" alt=""></a></td>
         <td colspan="2"><a href="about.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('about','','images/about_down.gif',1);"><img name="about" src="images/about_up.gif" width="99" height="47" border="0" alt=""></a></td>
         <td><a href="contact.php" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('contact','','images/contact_down.gif',1);"><img name="contact" src="images/contact_up.gif" width="97" height="47" border="0" alt=""></a></td>
         <td><img src="images/spacer.gif" width="1" height="47" border="0" alt=""></td>
      </tr>
   </table>
</div>
