
<style type="text/css">
a.email{
	font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	color: #000000;
	text-decoration: none;
}
a.email:hover{
	font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	color: #FFFFFF;
	text-decoration: none;
}
body
{
   vertical-align:middle;
   overflow: hidden;
   text-align: center;
   margin-left: auto;
   margin-right: auto;
   background-color: #666666;
}
div.body
{
   width: 756px;
   border-width: 1px 1px 2px 2px;
   border-style: solid;
   border-color: #000000;
   margin-top: 0px;
   background: #000000;
   padding-right: 0  px;
   position: relative;
   z-index:1;
   /*
   border: 1px solid #000000;
   background-image: url(black.bmp);
   */
}
div.body_main
{
   background: #000000;
   width: 100%;
   margin: 0px;
   border: 0px;
   padding: 0px;
}
div.about_photo
{
   border: 0px solid white;
   position: absolute;
   left: 25px;
   top: 170px;
   width: 220px;
   height: 250px;
}
div.about
{
   border: 0px dashed orange;
   position: absolute;
   left: 295px;
   top: 150px;
   width: 405px;
   height: 320px;
   z-index: 4;
   color: #000000;
	text-align: justify;
   font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	text-decoration: none;
}
div.contact_us
{
   border: 0px dashed orange;
   position: absolute;
   left: 105px;
   top: 130px;
   width: 585px;
   height: 320px;
   z-index: 4;
   color: #000000;
	text-align: justify;
   font-family: Arial, Verdana, Helvetica, sans-serif;
	font-size: 15px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	text-decoration: none;
}
div.photo_collage
{
   border: 0px dashed orange;
   width: 450px;
   height: 300px;
   position: absolute;
   left: 130px;
   top: 150px;
   z-index: 4;
}
div.photo_main
{
   border: 0px solid black;
   width: 350px;
   height: 300px;
   position: absolute;
   left: 50px;
   top: 150px;
   z-index: 4;
}
div.photo_album
{
   border: 0x solid green;
   width: 330px;
   height: 300px;
   position: absolute;
   justify: margin;
   padding: 10px 10px 10px 10px;
   right: 20px;
   top: 150px;
   z-index: 3;
   vertical-align: center;
}
img.mini
{
   padding: 0px;
   border: 0px;
   margin: 0px;
   position: relative;
   border: 1px solid #000000;
}
img.big
{
   padding: 0px;
   border: 0px;
   margin: 0px;
   position: relative;
   border: 1px solid #000000;
}
   div.mmSubMenu
   {
      z-index: 2; right: 25px;top:80px;
      position: absolute;
      text-align: center;
      border: 0px solid #0FF00F;
      width: 187px;
      height: 51px;
      padding: 3px 0px 0px 0px;
      margin: 0px 0px 0px 0px;
      background-image: url(images/contact_details_background.jpg);
      color:#FFFFFF;
   }
   div.mmSubMenuCell
   {
      height: 25px;
      /*
      width: <?php echo($button_width); ?>px;
      border-width: 0px;
      border-color: #000000;
      background-color: #999999;
      border-style: solid;
      padding: 0px;
      */
   }
   a.mmSubMenuCell:link{color:#000000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
   a.mmSubMenuCell:visited{color:#000000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
   a.mmSubMenuCell:hover{color:#FF0000;text-decoration:none;font: bold 11px arial, georgia, courier,helvetica;}
   
table
{
   margin: 0px 0px 0px 0px;
   border: 0px 0px 0px 0px;
   padding: 0px 0px 0px 0px;
}
td.bold
{
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: bold;
	font-variant: normal;
	color: #000000;
	text-decoration: none;
}
td
{
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	color: #000000;
	text-decoration: none;
}
input.textfield
{
 	color:#000000;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	width:210px;
	background-color:#FFFFFF;
	border-color:#333333;
	border-width:1px;
	border-style:solid;   
}
textarea.details
{
	color:#000000;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	width:390px;
	height:90px;
	background-color:#FFFFFF;
	border-color:#333333;
	border-width:1px;
	border-style:solid;
	overflow:hidden;
}
input.textfield_incomplete
{
 	color:#FFFFFF;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	font-style: normal;
	font-weight: normal;
	font-variant: normal;
	width:210px;
	background-color:#0000FF;
	border-color:#333333;
	border-width:1px;
	border-style:solid;   
}
</style>