<%@ LANGUAGE = PerlScript %>  
<!--#Include virtual="/component/Redirect.asp"-->
<%&CheckAccount('public','0');%>  
<!--#INCLUDE FILE="precontent.htm"-->
<h3>II. Creating an Internet and E-Mail Use Policy - Specific Content Checklist</h3><br>
<p><b>The below specific guidelines are written to help your business design an appropriate internet/e-mail use policy to serve its particular needs.  Other elements could also be contained within the policy, subject to your specific needs.</b></p>
<ul>
        <LI>The policy could notify employees that the systems are solely (or if desirable primarily) for business use, and that the company reserves the absolute right to review, audit and disclose all matters sent over the system or placed into its storage.  In addition to the written notification in the handbook or other written materials, ongoing notice to employees can be provided by programming a message that would appear on the employee’s monitor each time the employee accesses the system.  It would also specify that the employer reserves the right to access any messages or information entered into the system.</li>
        <LI>The policy could specify that the system should not be used to communicate any improper communications, e.g., messages which are derogatory, defamatory, obscene or, inappropriate.</li>
        <LI>To reduce any reasonable expectation of privacy, the policy should not limit your reasons for monitoring the system.  Any limitation could be argued to restrict the scope of the employee’s consent to the monitoring.  A more cautious approach would be to establish a business purpose that would be articulated in connection with any monitoring so as to defeat any possible expectation of privacy. </li>
        <LI>Consistent with the prohibition against non-business use of the system, the policy could be subject to the employer’s no-solicitation rule as could all other means of intra-company communication.  Such a rule would encompass any solicitation, whether for charitable, personal, business or union organizing purposes.  An alternative would be to allow access to an electronic bulletin board (that can be viewed by all employees) for solicitation and/or personal messages.</li>
        <LI>To further diminish the reasonable expectation of privacy, the policy could contain a warning that the mere deletion of a message or file may not fully eliminate the message from the system.</li>
        <LI>The policy could be accompanied by a form which employees could be required to sign acknowledging the business’ absolute right to access the system’s information.  Requiring employees to sign the form will further eliminate any expectation of privacy in the information transmitted and could prevent an employee from claiming that he/she was unaware of the policy.</li>
        <LI>The policy could make clear that a violation of the policy may result in disciplinary action up to and including discharge from employment.  The employer could also specify that any abuse of the system, e.g., inappropriate content, accessing files beyond those necessary by the employee (and/or use of the system for personal reasons) will result in disciplinary action. </li>
        <LI>Notwithstanding a strong policy statement permitting monitoring, actual monitoring of electronic communications could be limited to situations where such monitoring is necessary to protect your business purposes.  The least intrusive method of monitoring could be utilized and excessive intrusion into personal communications should be avoided.</li>
        <LI>In order to reduce the potential for defamation and/or invasion of privacy claims, disclosure of the information obtained from the system could be limited to those who have a legitimate need to know.</li>
</ul>    
<hr>
<center><a href="euse1.asp">[Previous]</a> <a href="euse3.asp">[Next]</a></center>
<!--#INCLUDE FILE="postcontent.htm"-->